In [ ]:
import pandas as pd
import plotly.express as px

file_path = '/content/Acceptance - Trust Scale (Responses) - Form responses 1.csv'
df = pd.read_csv(file_path)
df.drop(columns=['Timestamp'], inplace=True)
df.head()

,Participant ID,Choose the Experiment Condition,Personality Trait,I find such a system...,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,I trust that the autonomous vehicle will operate safely and effectively under various conditions [Please click one that applies]
0,1,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,2,Agree
1,1,C,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,3,Agree
2,2,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,1,Agree
3,2,C,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,1,Agree
4,3,A,High Neuroticism - Low Openness,1,2,4,2,2,5,2,5,2,Agree

In [ ]:
df.rename(columns={
    'Participant ID': 'participant_id',
    'Choose the Experiment Condition': 'experiment_condition',
    'Personality Trait': 'personality_trait',
    'I find such a system...': 'useful/useless',
    'Unnamed: 5': 'pleasant/unpleasant',
    'Unnamed: 6': 'bad/good',
    'Unnamed: 7': 'nice/annoying',
    'Unnamed: 8': 'effective/superfluous',
    'Unnamed: 9': 'irritating/likeable',
    'Unnamed: 10': 'assisting/worthless',
    'Unnamed: 11': 'undesirable/desirable',
    'Unnamed: 12': 'raising alertness/sleep-inducing',
    'I trust that the autonomous vehicle will operate safely and effectively under various conditions [Please click one that applies]': 'trust-safety-effectiveness'
}, inplace=True)

print(df.columns)

Index(['participant_id', 'experiment_condition', 'personality_trait',
       'useful/useless', 'pleasant/unpleasant', 'bad/good', 'nice/annoying',
       'effective/superfluous', 'irritating/likeable', 'assisting/worthless',
       'undesirable/desirable', 'raising alertness/sleep-inducing',
       'trust-safety-effectiveness'],
      dtype='object')

In [ ]:
df

,participant_id,experiment_condition,personality_trait,useful/useless,pleasant/unpleasant,bad/good,nice/annoying,effective/superfluous,irritating/likeable,assisting/worthless,undesirable/desirable,raising alertness/sleep-inducing,trust-safety-effectiveness
0,1,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,2,Agree
1,1,C,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,3,Agree
2,2,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,1,Agree
3,2,C,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,1,Agree
4,3,A,High Neuroticism - Low Openness,1,2,4,2,2,5,2,5,2,Agree
5,3,B,High Neuroticism - Low Openness,1,2,5,2,2,4,2,4,2,Agree
6,4,A,High Neuroticism - Low Openness,3,3,3,2,3,4,1,4,1,Agree
7,4,C,High Neuroticism - Low Openness,3,2,3,3,3,4,2,3,3,Agree
8,5,A,High Neuroticism - Low Openness,3,3,3,3,2,2,3,3,3,Neutral
9,5,B,High Neuroticism - Low Openness,3,4,3,3,4,2,4,3,3,Neutral
10,6,A,High Neuroticism - Low Openness,2,3,4,3,4,4,2,2,3,Strongly Disagree
11,6,C,High Neuroticism - Low Openness,2,4,2,4,4,2,4,3,3,Agree
12,7,A,High Openness - Low Neuroticism,2,2,5,2,1,4,1,5,2,Agree
13,7,B,High Openness - Low Neuroticism,2,2,5,1,2,5,2,4,4,Agree
14,8,A,High Openness - Low Neuroticism,1,2,5,1,1,5,1,4,1,Strongly Agree
15,8,C,High Openness - Low Neuroticism,2,2,5,2,2,5,2,4,2,Agree
16,9,A,High Neuroticism - Low Openness,1,1,5,1,5,5,1,5,4,Agree
17,9,B,High Neuroticism - Low Openness,2,3,3,3,4,4,2,4,4,Agree
18,10,A,High Openness - Low Neuroticism,1,1,4,2,1,4,2,5,3,Strongly Agree
19,10,C,High Openness - Low Neuroticism,1,2,4,1,1,4,1,5,3,Strongly Agree
20,11,A,High Openness - Low Neuroticism,2,3,4,2,4,4,3,4,2,Agree
21,11,B,High Openness - Low Neuroticism,5,4,2,4,4,2,4,2,4,Strongly Disagree
22,13,A,High Openness - Low Neuroticism,2,4,2,4,4,2,3,4,2,Disagree
23,12,C,High Openness - Low Neuroticism,2,4,2,4,4,2,2,4,2,Disagree
24,14,A,High Neuroticism - Low Openness,1,4,4,1,2,4,1,4,2,Agree
25,14,C,High Neuroticism - Low Openness,1,2,5,2,2,4,2,5,2,Strongly Agree
26,15,A,High Neuroticism - Low Openness,1,2,5,1,1,5,2,4,2,Agree
27,15,B,High Neuroticism - Low Openness,4,5,2,4,3,1,5,1,1,Disagree
28,16,A,High Openness - Low Neuroticism,2,1,4,2,2,4,2,4,1,Agree
29,16,C,High Openness - Low Neuroticism,2,1,4,1,2,5,2,4,1,Agree
30,17,A,High Neuroticism - Low Openness,1,2,5,2,2,4,2,5,2,Strongly Disagree
31,17,B,High Neuroticism - Low Openness,5,4,1,5,3,2,4,4,5,Strongly Disagree
32,18,A,High Openness - Low Neuroticism,1,2,5,1,4,4,2,4,3,Neutral
33,18,C,High Openness - Low Neuroticism,1,2,5,1,1,5,2,4,3,Agree
34,12,B,High Openness - Low Neuroticism,4,4,3,4,4,3,4,2,4,Agree
35,19,A,High Neuroticism - Low Openness,2,3,4,2,3,4,2,4,2,Disagree
36,19,B,High Neuroticism - Low Openness,3,3,4,2,2,4,4,3,4,Neutral
37,13,B,High Neuroticism - Low Openness,5,4,2,4,4,2,4,2,2,Disagree
38,20,A,High Openness - Low Neuroticism,1,2,5,2,4,4,2,4,3,Strongly Agree
39,20,C,High Openness - Low Neuroticism,1,1,2,2,4,2,2,3,3,Strongly Agree
40,21,A,High Neuroticism - Low Openness,1,1,4,2,1,4,1,5,3,Strongly Agree
41,21,B,High Neuroticism - Low Openness,1,1,5,1,1,5,1,5,4,Agree
42,22,A,High Neuroticism - Low Openness,2,2,4,1,2,5,1,5,2,Agree
43,22,C,High Neuroticism - Low Openness,4,4,4,3,3,4,4,3,4,Agree
44,23,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,1,Strongly Agree
45,23,B,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,2,Strongly Agree
46,24,A,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,3,Agree
47,24,C,High Openness - Low Neuroticism,1,1,5,1,1,5,1,5,3,Agree
48,25,A,High Neuroticism - Low Openness,2,1,4,2,4,4,4,3,2,Disagree
49,25,B,High Neuroticism - Low Openness,4,4,3,3,4,2,3,3,5,Disagree
50,26,A,High Neuroticism - Low Openness,1,1,5,1,2,5,1,5,3,Agree
51,26,C,High Neuroticism - Low Openness,5,4,2,4,4,4,4,3,5,Strongly Disagree
52,27,A,High Neuroticism - Low Openness,2,2,4,2,2,3,2,3,2,Neutral
53,27,B,High Neuroticism - Low Openness,4,4,2,3,3,2,4,2,4,Disagree

In [ ]:
import pandas as pd

# Assuming df is your DataFrame

# Update the map_score function to handle both kinds of mappings: from 1-5 scale and response strings
def map_score(score):
    if isinstance(score, int):  # Handle the 1-5 scale mapping
        mapping = {1: 2, 2: 1, 3: 0, 4: -1, 5: -2}
        return mapping[score]
    elif isinstance(score, str):  # Handle response string mapping
        mapping = {
            'Strongly Disagree': -2.0,
            'Disagree': -1.0,
            'Neutral': 0.0,
            'Agree': 1.0,
            'Strongly Agree': 2.0
        }
        return mapping[score]
    return None

# Apply the mapping to all relevant columns
score_columns = [
    'useful/useless', 'bad/good', 'effective/superfluous', 'assisting/worthless',
    'raising alertness/sleep-inducing', 'pleasant/unpleasant', 'nice/annoying',
    'irritating/likeable', 'undesirable/desirable', 'trust-safety-effectiveness'
]
for col in score_columns:
    df[col] = df[col].apply(map_score)

# Define the function to calculate Usefulness and Satisfying scores
def calculate_scores(row):
    # Calculating Usefulness
    usefulness = (
        row['useful/useless'] +
        (-row['bad/good']) +  # Mirrored
        row['effective/superfluous'] +
        row['assisting/worthless'] +
        row['raising alertness/sleep-inducing']
    ) / 5

    # Calculating Satisfying
    satisfying = (
        row['pleasant/unpleasant'] +
        row['nice/annoying'] +  # Mirrored
        (-row['irritating/likeable']) +  # Mirrored
        (-row['undesirable/desirable'])  # Mirrored
    ) / 4

    return pd.Series([usefulness, satisfying])

# Calculate Usefulness and Satisfying scores
df[['Usefulness', 'Satisfying']] = df.apply(calculate_scores, axis=1)

# Add Trust-Safety score to the DataFrame
df['Trust-Safety'] = df['trust-safety-effectiveness']

# Create a new DataFrame with the necessary columns
result_df = df[['participant_id', 'experiment_condition', 'Usefulness', 'Satisfying', 'Trust-Safety']]

# Display the updated DataFrame
print(result_df)

    participant_id experiment_condition  Usefulness  Satisfying  Trust-Safety
0                1                    A         1.8        2.00           1.0
1                1                    C         1.6        2.00           1.0
2                2                    A         2.0        2.00           1.0
3                2                    C         2.0        2.00           1.0
4                3                    A         1.2        1.50           1.0
5                3                    B         1.4        1.00           1.0
6                4                    A         0.8        0.75           1.0
7                4                    C         0.2        0.50           1.0
8                5                    A         0.2       -0.25           0.0
9                5                    B        -0.4       -0.50           0.0
10               6                    A         0.4        0.00          -2.0
11               6                    C        -0.4       -0.75           1.0
12               7                    A         1.6        1.25           1.0
13               7                    B         0.8        1.50           1.0
14               8                    A         2.0        1.50           2.0
15               8                    C         1.2        1.25           1.0
16               9                    A         0.6        2.00           1.0
17               9                    B         0.0        0.50           1.0
18              10                    A         1.2        1.50           2.0
19              10                    C         1.4        1.50           2.0
20              11                    A         0.4        0.75           1.0
21              11                    B        -1.2       -1.00          -2.0
22              13                    A         0.0       -0.50          -1.0
23              12                    C         0.2       -0.50          -1.0
24              14                    A         1.4        0.75           1.0
25              14                    C         1.4        1.25           2.0
26              15                    A         1.6        1.50           1.0
27              15                    B        -0.4       -1.75          -1.0
28              16                    A         1.2        1.25           1.0
29              16                    C         1.2        1.75           1.0
30              17                    A         1.4        1.25          -2.0
31              17                    B        -1.4       -0.75          -2.0
32              18                    A         0.8        1.25           0.0
33              18                    C         1.4        1.50           1.0
34              12                    B        -0.8       -0.75           1.0
35              19                    A         0.8        0.75          -1.0
36              19                    B         0.0        0.50           0.0
37              13                    B        -0.8       -1.00          -1.0
38              20                    A         0.8        1.00           2.0
39              20                    C         0.2        0.50           2.0
40              21                    A         1.4        1.50           2.0
41              21                    B         1.4        2.00           1.0
42              22                    A         1.2        1.75           1.0
43              22                    C        -0.4        0.00           1.0
44              23                    A         2.0        2.00           2.0
45              23                    B         1.8        2.00           2.0
46              24                    A         1.6        2.00           1.0
47              24                    C         1.6        2.00           1.0
48              25                    A         0.2        1.00          -1.0
49              25                    B        -0.8       -0.50          -1.0
50              26                    A         1.4        2.00           1.0
51              26                    C        -1.4       -0.25          -2.0
52              27                    A         1.0        0.50           0.0
53              27                    B        -0.8       -0.75          -1.0

In [ ]:
result_df

    participant_id experiment_condition  Usefulness  Satisfying  Trust-Safety
0                1                    A         1.8        2.00           1.0
1                1                    C         1.6        2.00           1.0
2                2                    A         2.0        2.00           1.0
3                2                    C         2.0        2.00           1.0
4                3                    A         1.2        1.50           1.0
5                3                    B         1.4        1.00           1.0
6                4                    A         0.8        0.75           1.0
7                4                    C         0.2        0.50           1.0
8                5                    A         0.2       -0.25           0.0
9                5                    B        -0.4       -0.50           0.0
10               6                    A         0.4        0.00          -2.0
11               6                    C        -0.4       -0.75           1.0
12               7                    A         1.6        1.25           1.0
13               7                    B         0.8        1.50           1.0
14               8                    A         2.0        1.50           2.0
15               8                    C         1.2        1.25           1.0
16               9                    A         0.6        2.00           1.0
17               9                    B         0.0        0.50           1.0
18              10                    A         1.2        1.50           2.0
19              10                    C         1.4        1.50           2.0
20              11                    A         0.4        0.75           1.0
21              11                    B        -1.2       -1.00          -2.0
22              13                    A         0.0       -0.50          -1.0
23              12                    C         0.2       -0.50          -1.0
24              14                    A         1.4        0.75           1.0
25              14                    C         1.4        1.25           2.0
26              15                    A         1.6        1.50           1.0
27              15                    B        -0.4       -1.75          -1.0
28              16                    A         1.2        1.25           1.0
29              16                    C         1.2        1.75           1.0
30              17                    A         1.4        1.25          -2.0
31              17                    B        -1.4       -0.75          -2.0
32              18                    A         0.8        1.25           0.0
33              18                    C         1.4        1.50           1.0
34              12                    B        -0.8       -0.75           1.0
35              19                    A         0.8        0.75          -1.0
36              19                    B         0.0        0.50           0.0
37              13                    B        -0.8       -1.00          -1.0
38              20                    A         0.8        1.00           2.0
39              20                    C         0.2        0.50           2.0
40              21                    A         1.4        1.50           2.0
41              21                    B         1.4        2.00           1.0
42              22                    A         1.2        1.75           1.0
43              22                    C        -0.4        0.00           1.0
44              23                    A         2.0        2.00           2.0
45              23                    B         1.8        2.00           2.0
46              24                    A         1.6        2.00           1.0
47              24                    C         1.6        2.00           1.0
48              25                    A         0.2        1.00          -1.0
49              25                    B        -0.8       -0.50          -1.0
50              26                    A         1.4        2.00           1.0
51              26                    C        -1.4       -0.25          -2.0
52              27                    A         1.0        0.50           0.0
53              27                    B        -0.8       -0.75          -1.0

In [ ]:
def assign_condition_number(row):
    # Map each condition to a number
    mapping = {'A': 0, 'B': 1, 'C': 2}
    return mapping.get(row['experiment_condition'], -1)  # Returns -1 if none of A, B, C

# Apply the function to create the new column
result_df['condition_number'] = result_df.apply(assign_condition_number, axis=1)

<ipython-input-6-9e60c9b5142f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['condition_number'] = result_df.apply(assign_condition_number, axis=1)

In [ ]:
result_df

,participant_id,experiment_condition,Usefulness,Satisfying,Trust-Safety,condition_number
0,1,A,1.8,2.00,1.0,0
1,1,C,1.6,2.00,1.0,2
2,2,A,2.0,2.00,1.0,0
3,2,C,2.0,2.00,1.0,2
4,3,A,1.2,1.50,1.0,0
5,3,B,1.4,1.00,1.0,1
6,4,A,0.8,0.75,1.0,0
7,4,C,0.2,0.50,1.0,2
8,5,A,0.2,-0.25,0.0,0
9,5,B,-0.4,-0.50,0.0,1
10,6,A,0.4,0.00,-2.0,0
11,6,C,-0.4,-0.75,1.0,2
12,7,A,1.6,1.25,1.0,0
13,7,B,0.8,1.50,1.0,1
14,8,A,2.0,1.50,2.0,0
15,8,C,1.2,1.25,1.0,2
16,9,A,0.6,2.00,1.0,0
17,9,B,0.0,0.50,1.0,1
18,10,A,1.2,1.50,2.0,0
19,10,C,1.4,1.50,2.0,2
20,11,A,0.4,0.75,1.0,0
21,11,B,-1.2,-1.00,-2.0,1
22,13,A,0.0,-0.50,-1.0,0
23,12,C,0.2,-0.50,-1.0,2
24,14,A,1.4,0.75,1.0,0
25,14,C,1.4,1.25,2.0,2
26,15,A,1.6,1.50,1.0,0
27,15,B,-0.4,-1.75,-1.0,1
28,16,A,1.2,1.25,1.0,0
29,16,C,1.2,1.75,1.0,2
30,17,A,1.4,1.25,-2.0,0
31,17,B,-1.4,-0.75,-2.0,1
32,18,A,0.8,1.25,0.0,0
33,18,C,1.4,1.50,1.0,2
34,12,B,-0.8,-0.75,1.0,1
35,19,A,0.8,0.75,-1.0,0
36,19,B,0.0,0.50,0.0,1
37,13,B,-0.8,-1.00,-1.0,1
38,20,A,0.8,1.00,2.0,0
39,20,C,0.2,0.50,2.0,2
40,21,A,1.4,1.50,2.0,0
41,21,B,1.4,2.00,1.0,1
42,22,A,1.2,1.75,1.0,0
43,22,C,-0.4,0.00,1.0,2
44,23,A,2.0,2.00,2.0,0
45,23,B,1.8,2.00,2.0,1
46,24,A,1.6,2.00,1.0,0
47,24,C,1.6,2.00,1.0,2
48,25,A,0.2,1.00,-1.0,0
49,25,B,-0.8,-0.50,-1.0,1
50,26,A,1.4,2.00,1.0,0
51,26,C,-1.4,-0.25,-2.0,2
52,27,A,1.0,0.50,0.0,0
53,27,B,-0.8,-0.75,-1.0,1

In [ ]:
result_df.to_excel(
  'acceptance_results.xlsx'
)